# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
  use_frameworks!

target 'WZMessageKitDemo' do
  pod 'WZReusableView', :path =>'/Users/fanyinan/Documents/MyGitHubProjects/WZReusableView'

end
