# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
  use_frameworks!

target 'WZMessageKitDemo' do
#  pod 'WZReusableView', :path =>'/Users/fanyinan/Documents/MyGitHubProjects/WZReusableView'
  pod 'WZReusableView', :git => 'https://github.com/fanyinan/WZReusableView'
  pod 'WZRichTextView', :git => 'https://github.com/fanyinan/RichTextView-Swift-3.0'

end
